### ISSUE TITLE
Rename "OTP validation API" to "OTPValidation" on the 

### ISSUE THREAD

**Issue by hdamker** [camaraproject/Marketing#5]
**Problem description**

Sub Project "OTP validation API" was renamed to "OTP Validation" (see https://github.com/camaraproject/OTPValidation/issues/75). This is not yet reflected on the web site of CAMARA.

**Expected behavior**

Update https://camaraproject.org/number-verification-sms-2fa/ with the content of https://github.com/camaraproject/OTPValidation/blob/r1.1/README.md
Update the Sub Project name within the Sub Project menu of the web site.

**Alternative solution**

**Additional context**

**Comment by MarkusKuemmerle** [comment]
Also CAMARA presentation has to be updated
